services:
  barravento:
    build: ./barravento/1_medium
    container_name: barravento
    ports:
      - "7077:7077"
      - "8080:8080"
      - "9200:9200"
      - "9870:9870"
      - "9000:9000"
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
    volumes:
      - ./requirements_python.txt:/root/requirements_python.txt:ro
    networks:
      - cluster_net
  jardimdealah:
    build: ./jardimdealah/1_medium
    container_name: jardimdealah
    volumes:
      - ./requirements_python.txt:/root/requirements_python.txt:ro
    networks:
      - cluster_net
  stellamaris:
    build: ./stellamaris/1_medium
    container_name: stellamaris
    volumes:
      - ./requirements_python.txt:/root/requirements_python.txt:ro
    networks:
      - cluster_net
  lagamar:
    build: ./lagamar
    container_name: lagamar
    ports:
      - "8888:8888"
      - "2222:22"
    volumes:
      - ./requirements_python.txt:/root/requirements_python.txt:ro
      - ./entrada/:/root/entrada/:rw
    networks:
      - cluster_net

networks:
  cluster_net:
    driver: bridge
